repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.1
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: script/run_pytest_changed.sh
        language: script
        files: ^(PySrDaliGateway|tests)/.*\.py$
        pass_filenames: true
